@authorization = Bearer {{login.response.body.accessToken}}
@slug_of_first_organization = {{organizations_where_user_is_member.response.body.$.[0].slug}}

# autenticado com o usuário default
# @name login
POST  {{apiUrl}}/signin/credentials
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
###


# organizações em que o usuário logado é membro
# @name organizations_where_user_is_member
GET  {{apiUrl}}/organizations
Authorization: {{authorization}}
###

# exibir organização pelo slug
# @name organization_by_slug
GET  {{apiUrl}}/organizations/{{slug_of_first_organization}}
Authorization: {{authorization}}
###

# criar projeto
# @name create_project
POST  {{apiUrl}}/organizations/{{slug_of_first_organization}}/projects
Authorization: {{authorization}}
Content-Type: application/json

{
  "name": "Projeto ABC",
  //"slug": "projeto-abc-2",
  "description": "Descição do projeto ABC",
  "avatar_url": "https://t3.ftcdn.net/jpg/04/52/55/40/360_F_452554046_OysDdSJkAjzouEUv5E1NKvbrSmmS9FAw.jpg"
}
###

# deletar projeto
# @name delete_project
DELETE {{apiUrl}}/organizations/{{slug_of_first_organization}}/projects/{{create_project.response.body.projectId}}
Authorization: {{authorization}}
###
