services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: saas
    ports:
      - '5432:5432'
    networks:
      - saas_network

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - saas_network

networks:
  saas_network:
